version: '3'
services:
  dev:
    image: node:8
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service
    command: bash -c "npm install && npm run dev"
    ports:
      - 8080:8080
